# Generated by Django 5.0.4 on 2024-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Оидание'), ('confirmed', 'Согласовано'), ('rejected', 'Отклонено')], default=True, max_length=20),
        ),
    ]
